name: CI

on: push

jobs:
  Build:
    runs-on: ubuntu-18.04

    env:
      GITHUB_READPACKAGES_USER: ${{ secrets.GH_READPACKAGES_USER }}
      GITHUB_READPACKAGES_TOKEN: ${{ secrets.GH_READPACKAGES_TOKEN }}
      S3_BASE_URL: s3://dl.eidu.com/
      S3_HTTP_BASE_URL: http://dl.eidu.com/

    steps:
      # This step serves as a workaround for not being able to use ${{ env.* }} in global env vars.
      - name: Set dynamic environment variables for test app
        run: |
          echo "S3_TEST_OBJECT_PATH=ci/content-test-app-$GITHUB_RUN_NUMBER.apk" >> $GITHUB_ENV
          echo "S3_SAMPLE_OBJECT_PATH=ci/content-sample-app-$GITHUB_RUN_NUMBER.apk" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - uses: actions/checkout@v2
      - name: Get tags for versioning the app
        run: git fetch --tags -f

      - name: Lint and test
        run: ./gradlew ktlintCheck ktlintTestSourceSetCheck ktlintAndroidTestSourceSetCheck lintCi testCiUnitTest --stacktrace

      - name: Publish test reports
        uses: actions/upload-artifact@v1
        with:
          name: test-reports
          path: app/build/reports/tests
        if: ${{ failure() }}

      - name: Build APKs
        run: ./gradlew assembleCi --stacktrace

      - name: Upload App APKs to S3
        run: |
          aws s3 cp content-test-app/build/outputs/apk/ci/content-test-app-ci.apk "${{ env.S3_BASE_URL }}${{ env.S3_TEST_OBJECT_PATH }}"
          aws s3 cp content-sample-app/build/outputs/apk/ci/content-sample-app-ci.apk "${{ env.S3_BASE_URL }}${{ env.S3_SAMPLE_OBJECT_PATH }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_UPLOAD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_UPLOAD_SECRET_ACCESS_KEY }}

      - name: "Post Slack message to #build"
        uses: EIDU/ci-notify-slack@v1.2
        with:
          job-status: ${{ job.status }}
          webhook: ${{ secrets.SLACK_WEBHOOK_BUILD_CHANNEL }}
          artifact-urls: >-
            ["${{ env.S3_HTTP_BASE_URL }}ci/content-sample-app-ci.apk-${{ env.RUN_NUMBER }}.apk",
            "${{ env.S3_HTTP_BASE_URL }}ci/content-test-app-ci.apk-${{ env.RUN_NUMBER }}.apk"]
        if: always()
